r"""LaTeX tables, ready to \input{} into the paper.

Required preamble in the paper:

    \usepackage{booktabs}

Nothing else: no siunitx, no multirow, no tabularx. Every table is a
self-contained `table` float that compiles on its own, so a broken table is
obvious immediately rather than at camera-ready.

Each file starts with `%` comment lines recording the generating command, the
timestamp, the grader version and the seeds, because a table in a paper whose
provenance nobody can reconstruct is a liability.
"""

from __future__ import annotations

import logging
import math
import shlex
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

from ..utils import utc_now_iso

log = logging.getLogger(__name__)

_LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def escape(text: Any) -> str:
    """Escape LaTeX specials. Model names are full of underscores and hyphens."""
    out = []
    for ch in str(text if text is not None else ""):
        out.append(_LATEX_ESCAPES.get(ch, ch))
    return "".join(out)


def _short(name: Any, limit: int = 28) -> str:
    text = str(name or "?").split("/")[-1]
    return text if len(text) <= limit else text[: limit - 1] + "..."


def _header(kind: str, extra: Sequence[str] = ()) -> List[str]:
    command = " ".join(shlex.quote(a) for a in [Path(sys.argv[0]).name, *sys.argv[1:]])
    lines = [
        f"% {kind} - generated by src/analysis/tables.py, do not edit by hand",
        f"% command   : {command}",
        f"% generated : {utc_now_iso()}",
    ]
    lines.extend(f"% {line}" for line in extra)
    lines.append(r"% requires  : \usepackage{booktabs}")
    return lines


def _provenance(summaries: Sequence[Dict[str, Any]]) -> List[str]:
    seeds = sorted({str(s.get("seed")) for s in summaries})
    graders = sorted({str(s.get("grader_version")) for s in summaries})
    backends = sorted({str(s.get("grader_backend")) for s in summaries})
    return [
        f"seeds     : {', '.join(seeds)}",
        f"grader    : {', '.join(graders)} (backend: {', '.join(backends)})",
        f"n runs    : {len(summaries)}",
    ]


def _fmt(value: Any, digits: int = 3, dash: str = "--") -> str:
    if value is None:
        return dash
    try:
        number = float(value)
    except (TypeError, ValueError):
        return escape(value)
    if math.isnan(number):
        return dash
    if math.isinf(number):
        return r"$\infty$"
    return f"{number:.{digits}f}"


def _fmt_int(value: Any, dash: str = "--") -> str:
    if value is None:
        return dash
    try:
        number = float(value)
    except (TypeError, ValueError):
        return escape(value)
    if math.isnan(number) or math.isinf(number):
        return dash
    return f"{int(round(number)):,}".replace(",", r"\,")


def _acc_with_ci(row: Dict[str, Any]) -> str:
    acc = float(row.get("accuracy") or 0.0)
    low, high = row.get("ci_low"), row.get("ci_high")
    if low is None or high is None:
        return f"{100 * acc:.1f}"
    return f"{100 * acc:.1f} \\small{{[{100 * float(low):.1f}, {100 * float(high):.1f}]}}"


def _stars(p: Optional[float]) -> str:
    if p is None:
        return ""
    if p < 0.001:
        return "$^{***}$"
    if p < 0.01:
        return "$^{**}$"
    if p < 0.05:
        return "$^{*}$"
    return ""


def _write(lines: Iterable[str], out_path: str | Path) -> Path:
    out_path = Path(out_path).with_suffix(".tex")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info("wrote %s", out_path)
    return out_path


# ---------------------------------------------------------------------- tables
def main_results_table(
    summaries: Sequence[Dict[str, Any]],
    out_path: str | Path,
    caption: str = (
        "Accuracy with 95\\% Wilson confidence intervals, sample counts and token "
        "cost per experiment cell. Best value per dataset in bold."
    ),
    label: str = "tab:main",
) -> Path:
    """Accuracy / samples / token-cost table, grouped by dataset."""
    lines = _header("Main results", _provenance(summaries))
    lines += [
        r"\begin{table}[t]",
        r"  \centering",
        r"  \small",
        r"  \begin{tabular}{llrrrr}",
        r"    \toprule",
        r"    Dataset & Strategy & Acc.\ (95\% CI) & $k$ & Tok./ex. & Tok./correct \\",
        r"    \midrule",
    ]

    datasets = sorted({str(s.get("dataset")) for s in summaries})
    for di, dataset in enumerate(datasets):
        rows = [s for s in summaries if str(s.get("dataset")) == dataset]
        rows.sort(key=lambda s: -float(s.get("accuracy") or 0.0))
        best_acc = max((float(r.get("accuracy") or 0.0) for r in rows), default=0.0)
        finite_costs = [
            float(r.get("tokens_per_correct"))
            for r in rows
            if math.isfinite(float(r.get("tokens_per_correct") or float("inf")))
        ]
        best_cost = min(finite_costs) if finite_costs else None
        for ri, row in enumerate(rows):
            acc_cell = _acc_with_ci(row)
            if abs(float(row.get("accuracy") or 0.0) - best_acc) < 1e-12:
                acc_cell = r"\textbf{" + acc_cell + "}"
            cost = row.get("tokens_per_correct")
            cost_cell = _fmt_int(cost)
            if (
                best_cost is not None
                and math.isfinite(float(cost or float("inf")))
                and abs(float(cost) - best_cost) < 1e-9
            ):
                cost_cell = r"\textbf{" + cost_cell + "}"
            lines.append(
                "    "
                + " & ".join(
                    [
                        escape(_short(dataset, 16)) if ri == 0 else "",
                        escape(_short(row.get("strategy"), 20)),
                        acc_cell,
                        _fmt_int(row.get("max_samples")),
                        _fmt_int(row.get("tokens_mean_completion")),
                        cost_cell,
                    ]
                )
                + r" \\"
            )
        if di < len(datasets) - 1:
            lines.append(r"    \midrule")

    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        f"  \\caption{{{caption}}}",
        f"  \\label{{{label}}}",
        r"\end{table}",
    ]
    return _write(lines, out_path)


def significance_table(
    comparisons: Sequence[Dict[str, Any]],
    out_path: str | Path,
    baseline: str = "baseline",
    caption: Optional[str] = None,
    label: str = "tab:significance",
) -> Path:
    """Paired comparisons against a baseline: delta, CI, McNemar p, stars."""
    n_bootstrap = next(
        (int(c.get("n_bootstrap") or 0) for c in comparisons if c.get("n_bootstrap")), 0
    )
    caption = caption or (
        f"Paired comparison against \\texttt{{{escape(baseline)}}} on identical "
        f"examples. $\\Delta$ is the accuracy difference in points, with a "
        f"percentile interval from a paired bootstrap over examples "
        f"({n_bootstrap:,} resamples). $p$ is McNemar's exact test on the "
        f"discordant pairs. $^{{*}}p<0.05$, $^{{**}}p<0.01$, $^{{***}}p<0.001$."
    ).replace(",", r"\,")

    lines = _header("Significance", [f"baseline  : {baseline}"])
    lines += [
        r"\begin{table}[t]",
        r"  \centering",
        r"  \small",
        r"  \begin{tabular}{llrrrr}",
        r"    \toprule",
        r"    Dataset & Strategy & Acc.\ & $\Delta$ & 95\% CI & $p$ \\",
        r"    \midrule",
    ]
    for c in comparisons:
        if not c.get("n_paired"):
            continue
        boot = c.get("paired_bootstrap") or {}
        mc = c.get("mcnemar") or {}
        p_value = mc.get("p_value")
        delta = 100.0 * float(c.get("delta") or 0.0)
        ci = (
            f"[{100 * float(boot.get('ci_low', 0.0)):+.1f}, "
            f"{100 * float(boot.get('ci_high', 0.0)):+.1f}]"
        )
        lines.append(
            "    "
            + " & ".join(
                [
                    escape(_short(c.get("dataset"), 14)),
                    escape(_short(c.get("label_b"), 20)),
                    f"{100 * float(c.get('accuracy_b') or 0.0):.1f}",
                    f"{delta:+.1f}" + _stars(p_value),
                    ci,
                    ("$<0.001$" if (p_value or 1) < 0.001 else _fmt(p_value, 3)),
                ]
            )
            + r" \\"
        )
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        f"  \\caption{{{caption}}}",
        f"  \\label{{{label}}}",
        r"\end{table}",
    ]
    return _write(lines, out_path)


def budget_table(
    summaries: Sequence[Dict[str, Any]],
    out_path: str | Path,
    weekly_quota_hours: float = 30.0,
    caption: Optional[str] = None,
    label: str = "tab:budget",
) -> Path:
    """Per-run wall-clock and GPU-hours against the weekly quota.

    A reproducibility table, and a useful one: it makes the compute cost of the
    experiments explicit instead of leaving a reader to guess.
    """
    caption = caption or (
        f"Compute cost per experiment cell. GPU-hours are session wall-clock on the "
        f"Kaggle free tier, against a weekly quota of {weekly_quota_hours:.0f} hours."
    )
    lines = _header("Budget", _provenance(summaries))
    lines += [
        r"\begin{table}[t]",
        r"  \centering",
        r"  \small",
        r"  \begin{tabular}{llrrrr}",
        r"    \toprule",
        r"    Dataset & Strategy & $n$ & Wall-clock (h) & GPU-h & Cum.\ GPU-h \\",
        r"    \midrule",
    ]
    cumulative = 0.0
    for row in summaries:
        hours = float(row.get("elapsed_seconds") or 0.0) / 3600.0
        gpu_hours = float(row.get("gpu_hours") or 0.0)
        cumulative += gpu_hours
        lines.append(
            "    "
            + " & ".join(
                [
                    escape(_short(row.get("dataset"), 14)),
                    escape(_short(row.get("strategy"), 20)),
                    _fmt_int(row.get("n")),
                    _fmt(hours, 2),
                    _fmt(gpu_hours, 2),
                    _fmt(cumulative, 2),
                ]
            )
            + r" \\"
        )
    lines += [
        r"    \midrule",
        "    "
        + " & ".join(["\\textbf{Total}", "", "", "", "", r"\textbf{" + _fmt(cumulative, 2) + "}"])
        + r" \\",
        r"    \bottomrule",
        r"  \end{tabular}",
        f"  \\caption{{{caption}}}",
        f"  \\label{{{label}}}",
        r"\end{table}",
    ]
    return _write(lines, out_path)


def write_all(
    summaries: Sequence[Dict[str, Any]],
    comparisons: Sequence[Dict[str, Any]],
    out_dir: str | Path,
    baseline: str = "baseline",
) -> List[Path]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = [
        main_results_table(summaries, out_dir / "tab_main_results"),
        budget_table(summaries, out_dir / "tab_budget"),
    ]
    if comparisons:
        written.append(
            significance_table(
                comparisons, out_dir / "tab_significance", baseline=baseline
            )
        )
    return written
